<div id="menuleft">
      				<div id="arrowright"><p class="articlespage"> &nbsp;&nbsp;&nbsp;&nbsp; Artykuły  </p></div>
      				
      				<?php if($this->items->count()): ?>
	
					<?php foreach($this->items as $item): ?>
	
					<div id="list">- <?php echo $item->i_name ?></div>
	 	  
					<?php endforeach; ?>

					<?php endif; ?> 
      				
</div> 

<div id="content">

	<?php if($this->items->count()): ?>
	
		<?php foreach($this->items as $item): ?>
	
			<div id="Articles">
				<div id="Title"><?php echo $item->i_name ?></div>
				<div class="text"><?php echo $item->i_text ?></div>
			</div>			
	 	  
		<?php endforeach; ?>

		<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination_slider.phtml', array('query' => $this->query)) ?>
	
	<?php endif; ?>

</div> 